### PR TITLE
Add: Missing CustomerCreditFacade

### LINKED ISSUE #14: Missing class CustomerCreditFacade
The class `CustomerCreditFacade` that is used when calling the `TransferFileFacadeFactory::createCustomerCredit()` method does not exist.

### PR DESCRIPTION
**Pull request by BenjaminPaap**
This should fix #14 and make the `TransferFileFacadeFactory` completely usable. I also updated the format within this change to `pain.001.003.03` and uploaded the new schemas for this format.

### CODE REVIEW

**Comment by alex-pex** [comment]
Hello,

I use the lib to generate direct debits and I'm working on credit transfers. I wanted to use TransferFileFacadeFactory::createCustomerCredit but I noticed the CustomerCreditFacade doesn't exist.

Can you merge the PR or do you need something else before merging?

**Comment by BenjaminPaap** [comment]
@monofone I reverted the changes of the variant for the pain format. You're right, we should leave the default variant as it is right now. But in case of the tests we should verify that every variant and version is ok. In my opinion this can now be merged safely.

**Comment by alex-pex** [comment]
Documentation should be updated. I'll use your feature today, I can write the example code if you want.

**Comment by BenjaminPaap** [comment]
We welcome any pull request. So if you could provide that after using it we would be very happy.

**Pull request merged**
