### PR TITLE
Pass the withSchemaLocation boolean in DomBuilder constructors

### PR DESCRIPTION
**Pull request by mogilvie**
Factory method needs to pass this option through to the base abstract class.

### CODE REVIEW

**Comment by monofone** [comment]
This does not need to become a constructor argument as this is managed by the pain format, if you pass the correct pain Format (008.03.02)  the fields with the location are filled automatically if the data is provided in the transaction information.

**Comment by mogilvie** [comment]
The schemaLocation is being generated for credit transfers using 001.001.003.

Ulster Bank is rejecting the SEPA document based on it no complying with their published 
[2016 schema](https://www.google.ie/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwif_Y6alqPaAhWmDsAKHd4CDYkQFggpMAA&url=https%3A%2F%2Fdigital.ulsterbank.ie%2Fcontent%2Fdam%2FUlster%2Fdocuments%2FRI%2520Region%2Fri-business-banking-brochures%2Fgenerate-a-valid-bankline-sepa-money-transfer-file-RIBUSPDF0124.pdf&usg=AOvVaw2qVl0yaivR-PAp8u3-ORmT)

At the moment I am working around this by removing the attribute with str_replace after the XML has been constructed.

I'm not saying that Ulster bank are correct in their validation of submitted formatted Sepa, nevertheless, I'll still need to create payments.

You can decide if this constructor option is necessary.

**Comment by mogilvie** [comment]
Damn, last comment sound passive aggressive on rereading. I just mean I can keep using the str_replace for my needs.
Thanks

**Comment by monofone** [comment]
It seems there was a misunderstanding, I'm not a native english speaker ...

I will take a more narrow look into it. Maybe you can provide a testcase, my fear is the overloading of the constructor for too many edge cases. So an options DTO would be a better way to go here...

**Comment by monofone** [comment]
Damn, I now understand this issue and the source of the pull request, the already existing parameter was not brought to the outside.

**Comment by monofone** [comment]
@mogilvie is it possible for you to rebase your changes on the current master, that would be great.

**Pull request closed without merging**
