### PR TITLE
Added amendments support.

### PR DESCRIPTION
**Pull request by jarnovanleeuwen**
Hi,

This pull requests adds support for amendments. Currently it supports amendments in mandate id, debtor account and debtor agent, but can easily be extended to support more amendments.

Usage:

```php
// Add a Single Transaction to the named payment
$directDebit->addTransfer('firstPayment', array(
    'amount'                => '500',
    'debtorIban'            => 'FI1350001540000056',
    'debtorBic'             => 'OKOYFIHH',
    'debtorName'            => 'Their Company',
    'debtorMandate'         => 'AB12345',
    'debtorMandateSignDate' => '13.10.2012',
    'remittanceInformation' => 'Purpose of this direct debit',
    // Amendments start here
    'originalMandateId'     => '1234567890',
    'originalDebtorIban'    => 'AT711100015440033700',
    'amendedDebtorAgent'    => true
));
```

Greetings,
Jarno

### CODE REVIEW

**Comment by monofone** [comment]
Great, thanks for your contribution, do you mind to add a test somehow to check the correct structure ? And can you link to a .dtd lining out the structure of the amendment information, I don`t even know there ist one :-)

**Comment by jarnovanleeuwen** [comment]
Sure, I might add a test later on. It is surprisingly hard to find a good SEPA library with support for amendments. The structure can be found here: https://github.com/php-sepa-xml/php-sepa-xml/blob/master/tests/pain.008.001.02.xsd#L50

**Comment by monofone** [comment]
Ok, I`ll merge it after you`ve added a test and create a new release, thanks for the link to the dtd, seems to me I have some homework to do.

**Comment by monofone** [comment]
I`m going to close this in favor of #20

**Pull request closed without merging**
